kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hhh-jiva-sc
spec:
  storageClassName: openebs-jiva-csi-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi