apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: huanghuanghui
data:
  server_name: "myapp.magedu.com"
  nginx_port: "80"

---


apiVersion: v1
kind: Pod
metadata:
  name: pod-cm-1
  namespace: huanghuanghui
  labels: 
    app: pod-cm-1
    tier: frontend
spec:
  containers:
  - name: myapp
    image: huanghuanghui/myapp:v1
    imagePullPolicy: Never
    ports:
    - name: http
      containerPort: 80 
    env:
    # 可以echo $NGINX_SERVER_NAME/echo $NGINX_SERVER_PORT 从环境变量中拿到值
    - name: NGINX_SERVER_PORT
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: nginx_port
    - name: NGINX_SERVER_NAME
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: server_name