---
- name: install nginx
  yum: 
    name: nginx
    state: present
  when: "'nginx' in group_names"


- name: render and copy nginx config
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: true
    validate: "/usr/sbin/nginx -t -c %s"
  when: "'nginx' in group_names"
  notify: "reload nginx"


