apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia-rs-me
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - "kubia-rs"
          - "kubia-rc"
  template:
    metadata:
      name: kubia-rs-me
      labels:
        app: kubia-rs
    spec:
      containers:
        - name: kubia-rs
          image: huanghuanghui/kubia
          ports:
            - containerPort: 8080
