---
- name: this is a lineinfile
  hosts: localhost
  gather_facts: false
  tasks:
    - lineinfile:
        path: /Users/hhh/workspace/gitbook/docs/ansible/a.txt
        line: "#this is ansible lineinfile add"
        regexp: "^#this"
        insertbefore: '^para.* 2'