---
- name: set hostname
  hosts: new
  gather_facts: false
  vars:
    hostnames:
      - host: 10.210.13.4
        name: node1
      - host: 10.210.13.33
        name: node2
      - host: 10.210.13.36
        name: node3
  tasks: 
    - name: set hostname
      hostname: 
        name: "{{item.name}}"
      when: item.host == inventory_hostname
      loop: "{{hostnames}}"