---
- name: task1
  debug:
    msg: "task in my_var: {{my_var}}"

- name: include t.yml
  import_tasks: t.yml


- name: yum install ntp
  yum:
    name: ntp
    state: present
  tags:
    - initialize
    - pkginstall
    - ntp

- name: started ntpd
  service:
    name: ntpd
    state: started
  tags:
    - ntp
    - initialize
    -

[nginx]
10.210.13.4 ansible_user=root

[php]
10.210.13.33 ansible_user=root

[mysql]
10.210.13.36 ansible_user=root

[dev:children]
nginx
php
mysql


作者: 骏马金龙
链接: https://www.junmajinlong.com/ansible/7_role_examples/
来源: 骏马金龙
  著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。